"""Reusable ML utilities for notebooks and model projects."""

from .ml_utils import (
    format_duration,
    normalize_images,
    normalize_splits,
    ensure_label_indices,
    random_cutout,
    build_tf_dataset,
    extract_final_history_metrics,
    compute_classification_metrics,
    predict_and_resolve_labels,
    compute_confusion_matrix,
    build_classification_report,
    evaluate_and_log_model,
    log_metrics_to_csv,
    make_run_log_dir,
    apply_notebook01_plot_style,
    plot_confusion_matrix_notebook01,
    plot_training_curves_notebook01,
)

__all__ = [
    "format_duration",
    "normalize_images",
    "normalize_splits",
    "ensure_label_indices",
    "random_cutout",
    "build_tf_dataset",
    "extract_final_history_metrics",
    "compute_classification_metrics",
    "predict_and_resolve_labels",
    "compute_confusion_matrix",
    "build_classification_report",
    "evaluate_and_log_model",
    "log_metrics_to_csv",
    "make_run_log_dir",
    "apply_notebook01_plot_style",
    "plot_confusion_matrix_notebook01",
    "plot_training_curves_notebook01",
]
